src/Entity/Formationn.php
<?php

namespace App\Entity;

use App\Repository\FormationnRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\DBAL\Types\Types;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: FormationnRepository::class)]
class Formationn
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: "AUTO")]
    #[ORM\Column(name: "id_formation", type: "integer")]
    #[Groups("post:read")]
    private ?int $id_formation;

    #[ORM\ManyToOne(targetEntity: Niveau::class)]
    #[ORM\JoinColumn(name: "id_niveau", referencedColumnName: "id")]
    #[Groups("post:read")]
    private ?Niveau $niveau = null;

    #[ORM\Column(length: 255)]
    #[Groups("post:read")]
    private ?string $categorie = null;

    #[ORM\Column(length: 255)]
    #[Groups("post:read")]
    private ?string $titre = null;

    #[ORM\Column(length: 500)]
    #[Groups("post:read")]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups("post:read")]
    private ?\DateTimeInterface $date_d = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups("post:read")]
    private ?\DateTimeInterface $date_f = null;

    #[ORM\Column(length: 500)]
    #[Groups("post:read")]
    private ?string $lien = null;

    #[ORM\Column(length: 255)]
    #[Groups("post:read")]
    private ?string $pdfFilename = null;

    #[ORM\OneToMany(targetEntity: "App\Entity\Quiz", mappedBy: "formation")]
    #[Groups("post:read")]
    private $quizzes;

    public function __construct()
    {
        $this->quizzes = new ArrayCollection();
    }

    /**
     * @return Collection|Quiz[]
     */
    public function getQuizzes(): Collection
    {
        return $this->quizzes;
    }

    public function addQuiz(Quiz $quiz): self
    {
        if (!$this->quizzes->contains($quiz)) {
            $this->quizzes[] = $quiz;
            $quiz->setFormation($this);
        }

        return $this;
    }

    public function removeQuiz(Quiz $quiz): self
    {
        if ($this->quizzes->contains($quiz)) {
            $this->quizzes->removeElement($quiz);
            // set the owning side to null (unless already changed)
            if ($quiz->getFormation() === $this) {
                $quiz->setFormation(null);
            }
        }

        return $this;
    }

    public function getPdfFilename(): ?string
    {
        return $this->pdfFilename;
    }

    public function setPdfFilename(?string $pdfFilename): self
    {
        $this->pdfFilename = $pdfFilename;

        return $this;
    }


    public function getIdformation(): ?int
    {
        return $this->id_formation;
    }

    public function getNiveau(): ?Niveau
    {
        return $this->niveau;
    }

    public function setNiveau(?Niveau $niveau): self
    {
        $this->niveau = $niveau;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDateD(): ?\DateTimeInterface
    {
        return $this->date_d;
    }

    public function setDateD(\DateTimeInterface $date_d): static
    {
        $this->date_d = $date_d;

        return $this;
    }

    public function getDateF(): ?\DateTimeInterface
    {
        return $this->date_f;
    }

    public function setDateF(\DateTimeInterface $date_f): static
    {
        $this->date_f = $date_f;

        return $this;
    }

    public function getLien(): ?string
    {
        return $this->lien;
    }

    public function setLien(string $lien): static
    {
        $this->lien = $lien;

        return $this;
    }

}

src/Controller/FormationController.php
<?php

namespace App\Controller;

use App\Entity\Formationn;
use App\Form\FormationnType;
use App\Repository\FormationnRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\Process;
use Symfony\Component\Serializer\SerializerInterface;

#[Route('/formation')]
class FormationController extends AbstractController
{
    #[Route('/', name: 'app_formation_index', methods: ['GET'])]
    public function index(FormationnRepository $formationnRepository): Response
    {
        return $this->render('back/formation/index.html.twig', [
            'formationns' => $formationnRepository->findAll(),
        ]);
    }

    #[Route('/front', name: 'app_formation_index_front', methods: ['GET'])]
    public function indexFront(FormationnRepository $formationnRepository): Response
    {
        return $this->render('front/formation/index.html.twig', [
            'formationns' => $formationnRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_formation_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $formation = new Formationn();
        $form = $this->createForm(FormationnType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pdfFile = $form->get('pdfFile')->getData();
            if (!$form->get('pdfFile')->isEmpty()) {
                if ($pdfFile instanceof UploadedFile) {
                    $originalFilename = pathinfo($pdfFile->getClientOriginalName(), PATHINFO_FILENAME);
                    $newFilename = $originalFilename.'-'.uniqid().'.'.$pdfFile->guessExtension();

                    try {
                        $pdfFile->move(
                            $this->getParameter('pdf_directory'),
                            $newFilename
                        );
                    } catch (FileException $e) {
                        // Handle the file exception if needed
                    }

                    $formation->setPdfFilename($newFilename);
                }
            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($formation);
            $entityManager->flush();
            return $this->redirectToRoute('app_formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('back/formation/new.html.twig', [
            'formation' => $formation,
            'form' => $form->createView(),
        ]);
    }

    #[Route('front/new', name: 'app_formation_new_front', methods: ['GET', 'POST'])]
    public function newfront(Request $request): Response
    {
        $formation = new Formationn();
        $form = $this->createForm(FormationnType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pdfFile = $form->get('pdfFile')->getData();
            if (!$form->get('pdfFile')->isEmpty()) {
                if ($pdfFile instanceof UploadedFile) {
                    $originalFilename = pathinfo($pdfFile->getClientOriginalName(), PATHINFO_FILENAME);
                    $newFilename = $originalFilename.'-'.uniqid().'.'.$pdfFile->guessExtension();

                    try {
                        $pdfFile->move(
                            $this->getParameter('pdf_directory'),
                            $newFilename
                        );
                    } catch (FileException $e) {
                        // Handle the file exception if needed
                    }

                    $formation->setPdfFilename($newFilename);
                }
            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($formation);
            $entityManager->flush();

            return $this->redirectToRoute('app_formation_index_front', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('front/formation/new.html.twig', [
            'formation' => $formation,
            'form' => $form->createView(),
        ]);
    }

    

    #[Route('/show/{Idformation}', name: 'app_formation_show', methods: ['GET'])]
    public function show($Idformation,FormationnRepository $formationnRepository): Response
    {
        $formationn = $formationnRepository->find($Idformation);

        return $this->render('back/formation/show.html.twig', [
            'formationn' => $formationn,
        ]);
    }

    #[Route('/edit/{Idformation}', name: 'app_formation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, $Idformation, FormationnRepository $formationnRepository,EntityManagerInterface $entityManager): Response
    {

        $formationn = $formationnRepository->find($Idformation);


        $form = $this->createForm(FormationnType::class, $formationn);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $pdfFile = $form->get('pdfFile')->getData();
            if (!$form->get('pdfFile')->isEmpty()) {
                if ($pdfFile instanceof UploadedFile) {
                    $originalFilename = pathinfo($pdfFile->getClientOriginalName(), PATHINFO_FILENAME);
                    $newFilename = $originalFilename.'-'.uniqid().'.'.$pdfFile->guessExtension();

                    try {
                        $pdfFile->move(
                            $this->getParameter('pdf_directory'),
                            $newFilename
                        );
                    } catch (FileException $e) {
                        // Handle the file exception if needed
                    }

                    $formationn->setPdfFilename($newFilename);
                }
            }

            $entityManager->flush();

            return $this->redirectToRoute('app_formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/formation/edit.html.twig', [
            'formationn' => $formationn,
            'form' => $form,
        ]);
    }

    #[Route('/edit_front/{Idformation}', name: 'app_formation_edit_front', methods: ['GET', 'POST'])]
    public function editfront(Request $request, $Idformation,FormationnRepository $formationnRepository, EntityManagerInterface $entityManager): Response
    {
        $formationn = $formationnRepository->find($Idformation);

        $form = $this->createForm(FormationnType::class, $formationn);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $pdfFile = $form->get('pdfFile')->getData();
            if (!$form->get('pdfFile')->isEmpty()) {
                if ($pdfFile instanceof UploadedFile) {
                    $originalFilename = pathinfo($pdfFile->getClientOriginalName(), PATHINFO_FILENAME);
                    $newFilename = $originalFilename.'-'.uniqid().'.'.$pdfFile->guessExtension();

                    try {
                        $pdfFile->move(
                            $this->getParameter('pdf_directory'),
                            $newFilename
                        );
                    } catch (FileException $e) {
                        // Handle the file exception if needed
                    }

                    $formationn->setPdfFilename($newFilename);
                }
            }

            $entityManager->flush();
    
            return $this->redirectToRoute('app_formation_index_front', [], Response::HTTP_SEE_OTHER);
        }
    
        return $this->renderForm('front/formation/edit.html.twig', [
            'formationn' => $formationn,
            'form' => $form,
        ]);
    }



    #[Route('/delete/{Idformation}', name: 'app_formation_delete', methods: ['POST'])]
    public function delete(Request $request, $Idformation, EntityManagerInterface $entityManager, FormationnRepository $formationnRepository): Response
    {
        $formationn = $formationnRepository->find($Idformation);

        if (!$formationn) {
            throw $this->createNotFoundException('Formation not found');
        }

        foreach ($formationn->getQuizzes() as $quiz) {
            $entityManager->remove($quiz);
        }

        $entityManager->remove($formationn);
        $entityManager->flush();

        // Redirect to the index page or any other appropriate page after deletion
        return $this->redirectToRoute('app_formation_index', [], Response::HTTP_SEE_OTHER);
    }


    #[Route('/front/{Idformation}', name: 'app_formation_delete_front', methods: ['POST'])]
    public function deleteFront(Request $request, $Idformation, EntityManagerInterface $entityManager,FormationnRepository $formationnRepository): Response
    {
        $formationn = $formationnRepository->find($Idformation);

            $quizzes = $formationn->getQuizzes();

            foreach ($quizzes as $quiz) {
                $entityManager->remove($quiz);
            }
            $entityManager->flush();
            $entityManager->remove($formationn);
            $entityManager->flush();


        return $this->redirectToRoute('app_formation_index_front', [], Response::HTTP_SEE_OTHER);
    }

    //*****************google meet****************//

    #[Route('/open-link', name: 'open_link', methods: ['POST'])]
    public function openLink(Request $request): Response
    {
        $formationId = $request->request->get('Idformation');
        

templates/front/formation/_delete_form.html.twig
<form method="post" action="{{ path('app_formation_delete', {'id_formation': formationn.id_formation}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formationn.id_formation) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/front/formation/_form.html.twig
{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}

<div class="form-group">
    {{ form_label(form.niveau, 'Level') }} {# Update the field name to "niveau" #}
    {{ form_widget(form.niveau, {'attr': {'class': 'form-control'}}) }} {# Update the field name to "niveau" #}
    {% if form_errors(form.niveau)|length > 0 %} {# Update the field name to "niveau" #}
        <div class="alert alert-danger">{{ form_errors(form.niveau) }}</div> {# Update the field name to "niveau" #}
    {% endif %}
</div>

<div class="form-group">
    {{ form_label(form.categorie, 'Category') }}
    {{ form_widget(form.categorie, {'attr': {'class': 'form-control'}}) }}
    {% if form_errors(form.categorie)|length > 0 %}
        <div class="alert alert-danger">{{ form_errors(form.categorie) }}</div>
    {% endif %}
</div>

<div class="form-group">
    {{ form_label(form.titre, 'Title') }}
    {{ form_widget(form.titre, {'attr': {'class': 'form-control'}}) }}
    {% if form_errors(form.titre)|length > 0 %}
        <div class="alert alert-danger">{{ form_errors(form.titre) }}</div>
    {% endif %}
</div>

<div class="form-group">
    {{ form_label(form.description, 'Description') }}
    {{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
    {% if form_errors(form.description)|length > 0 %}
        <div class="alert alert-danger">{{ form_errors(form.description) }}</div>
    {% endif %}
</div>

<div class="form-row">
    <div class="col">
        <div class="form-group">
            {{ form_label(form.date_d, 'Debut Date') }}
            {{ form_widget(form.date_d, {'attr': {'class': 'form-control'}}) }}
            {% if form_errors(form.date_d)|length > 0 %}
                <div class="alert alert-danger">{{ form_errors(form.date_d) }}</div>
            {% endif %}
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            {{ form_label(form.date_f, 'Last Date') }}
            {{ form_widget(form.date_f, {'attr': {'class': 'form-control'}}) }}
            {% if form_errors(form.date_f)|length > 0 %}
                <div class="alert alert-danger">{{ form_errors(form.date_f) }}</div>
            {% endif %}
        </div>
    </div>
</div>

<div class="form-group">
    {{ form_label(form.lien, 'Link') }}
    {{ form_widget(form.lien, {'attr': {'class': 'form-control'}}) }}
    {% if form_errors(form.lien)|length > 0 %}
        <div class="alert alert-danger">{{ form_errors(form.lien) }}</div>
    {% endif %}
</div>
<div class="form-group">
    {{ form_label(form.pdfFile, 'Pdf') }}
    {{ form_widget(form.pdfFile, {'attr': {'class': 'form-control'}}) }}
    {% if form_errors(form.pdfFile)|length > 0 %}
        <div class="alert alert-danger">{{ form_errors(form.pdfFile) }}</div>
    {% endif %}
</div>

<div class="text-center">
    <button type="submit" class="btn btn-primary">{{ button_label }}</button>
    <a href="{{ path('app_formation_index_front') }}" class="btn btn-secondary">Back to List</a>
</div>

{{ form_end(form) }}

{% if form.vars.errors|length > 0 %}
    <div class="alert alert-danger mt-3">
        {{ form_errors(form) }}
    </div>
{% endif %}

templates/front/formation/edit.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}Modifier Cour{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1 class="text-center mb-4">Modifier Cour</h1>

        <div class="card">
            <div class="card-header bg-primary text-white">
                <h5 class="card-title">Modifier Cour</h5>
            </div>
            <div class="card-body">
                {{ include('front/formation/_form.html.twig', {'button_label': 'Update'}) }}
            </div>
        </div>

    </div>
{% endblock %}

templates/front/formation/new.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}Ajouter Cour{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1 class="text-center mb-4">Ajouter Cour</h1>

        <div class="card">
            <div class="card-header bg-primary text-white">
                <h5 class="card-title">Ajouter Cour</h5>
            </div>
            <div class="card-body">
                {{ include('front/formation/_form.html.twig', {'button_label': 'Ajouter'}) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/front/formation/show.html.twig
{% extends '/front/gestion.html.twig' %}

{% block title %}Formation Details{% endblock %}

{% block body %}
    <div class="container">
        <h1>Formation Details</h1>

        <table class="table table-bordered">
            <tbody>
                <tr>
                    <th scope="row">Id</th>
                    <td>{{ formationn.id_formation }}</td>
                </tr>
                <tr>
                    <th scope="row">Nom Niveau</th>
                    <td>{{ formationn.nomNiveau }}</td>
                </tr>
                <tr>
                    <th scope="row">Categorie</th>
                    <td>{{ formationn.categorie }}</td>
                </tr>
                <tr>
                    <th scope="row">Titre</th>
                    <td>{{ formationn.titre }}</td>
                </tr>
                <tr>
                    <th scope="row">Description</th>
                    <td>{{ formationn.description }}</td>
                </tr>
                <tr>
                    <th scope="row">Date de Début</th>
                    <td>{{ formationn.dateD ? formationn.dateD|date('Y-m-d') : '' }}</td>
                </tr>
                <tr>
                    <th scope="row">Date de Fin</th>
                    <td>{{ formationn.dateF ? formationn.dateF|date('Y-m-d') : '' }}</td>
                </tr>
                <tr>
                    <th scope="row">Lien</th>
                    <td>{{ formationn.lien }}</td>
                </tr>
            </tbody>
        </table>

        <a href="{{ path('app_formation_index') }}" class="btn btn-primary">Back to List</a>
        <a href="{{ path('app_formation_edit_front', {'id_formation': formationn.idFormation}) }}" class="btn btn-warning">Edit</a>

        {{ include('back/formation/_delete_form.html.twig') }}
    </div>
{% endblock %}