src/Entity/Tuteur.php
<?php

namespace App\Entity;

use App\Repository\TuteurRepository;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TuteurRepository::class)]
class Tuteur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_tuteur = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Name is required")]
    #[Assert\Length(min: 3, minMessage: "Name must be at least {{ limit }} characters")]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "First name is required")]
    #[Assert\Length(min: 4, minMessage: "First name must be at least {{ limit }} characters")]
    private ?string $prenom = null;

    #[ORM\Column(type: "datetime")]
    #[Assert\LessThan("today", message: "The date of birth must be in the past.")]
    private ?DateTimeInterface $date_naisc;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Phone number is required")]
    #[Assert\Regex(pattern: "/^\d{8}$/", message: "Phone number must be exactly 8 digits")]
    private ?int $tlf = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Profession is required")]
    #[Assert\Length(min: 3, minMessage: "Profession must be at least {{ limit }} characters")]
    private ?string $profession = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Email is required")]
    #[Assert\Email(message: "Please enter a valid email address")]
    private ?string $email = null;

    #[ORM\Column(nullable: false, length: 255)]
    private ?string $image;




    public function getId_tuteur(): ?int
    {
        return $this->id_tuteur;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaisc(): ?\DateTimeInterface
    {
        return $this->date_naisc;
    }

    public function setDateNaisc(\DateTimeInterface $date_naisc): static
    {
        $this->date_naisc = $date_naisc;

        return $this;
    }

    public function getTlf(): ?int
    {
        return $this->tlf;
    }

    public function setTlf(int $tlf): static
    {
        $this->tlf = $tlf;

        return $this;
    }

    public function getProfession(): ?string
    {
        return $this->profession;
    }

    public function setProfession(string $profession): static
    {
        $this->profession = $profession;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/TuteurType.php
<?php

namespace App\Form;

use App\Entity\Tuteur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType; 
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;


class TuteurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('nom')
        ->add('prenom')
        ->add('date_naisc', BirthdayType::class, [
            'label' => 'Date de naissance',
            'format' => 'dd-MM-yyyy', // Format complet de la date
            // Configuration pour inclure des années antérieures à 2019
            'years' => range(1950, 2003),
        ])
        ->add('tlf')
        ->add('profession')
        ->add('email')
        ->add('image', FileType::class, [
            'label' => false,
            'mapped' => false,
            'required' => false,
        ]);
        
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tuteur::class,
        ]);
    }
}

src/Controller/TuteurController.php
<?php

namespace App\Controller;

use App\Entity\Tuteur;
use App\Form\TuteurType;
use App\Repository\TuteurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/tuteur')]
class TuteurController extends AbstractController
{
    #[Route('/', name: 'app_tuteur_index', methods: ['GET'])]
    public function index(TuteurRepository $tuteurRepository): Response
    {
        return $this->render('tuteur/index.html.twig', [
            'tuteurs' => $tuteurRepository->findAll(),
        ]);
    }
    #[Route('/new', name: 'app_tuteur_new', methods: ['GET', 'POST'])]
public function new(Request $request, EntityManagerInterface $entityManager): Response
{
    $tuteur = new Tuteur();
    $form = $this->createForm(TuteurType::class, $tuteur);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $entityManager->persist($tuteur);
        $entityManager->flush();

        return $this->redirectToRoute('app_tuteur_index', [], Response::HTTP_SEE_OTHER);
    }

    return $this->render('tuteur/new.html.twig', [
        'form' => $form->createView(),
    ]);
}



    #[Route('/list', name: 'app_tuteur')]
public function listTuteurs(): Response
{
    
    $tuteur = $this->getDoctrine()->getRepository(Tuteur::class)->findAll();

    
    return $this->render('tuteur/show.html.twig', [
        'tuteur' => $tuteur,
    ]);
}

#[Route('/listb', name: 'back')]
public function listTuteur(): Response
{
    
    $tuteur = $this->getDoctrine()->getRepository(Tuteur::class)->findAll();

    
    return $this->render('tuteur/listback.html.twig', [
        'tuteur' => $tuteur,
    ]);
}

#[Route('/{id_tuteur}/edit', name: 'app_tuteur_edit', methods: ['GET', 'POST'])]
public function edit(Request $request, Tuteur $tuteur, EntityManagerInterface $entityManager): Response
{
    $form = $this->createForm(TuteurType::class, $tuteur);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $entityManager->flush();

        return $this->redirectToRoute('app_tuteur_index', [], Response::HTTP_SEE_OTHER);
    }

    return $this->renderForm('tuteur/edit.html.twig', [
        'tuteur' => $tuteur,
        'form' => $form,
    ]);
}


    #[Route('/{id_tuteur}', name: 'app_tuteur_delete', methods: ['POST'])]
    public function delete(Request $request, Tuteur $tuteur, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tuteur->getId_tuteur(), $request->request->get('_token'))) {
            $entityManager->remove($tuteur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_tuteur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/tuteur/_delete_form.html.twig
<form method="post" action="{{ path('app_tuteur_delete', {'idTuteur': tuteur.idTuteur}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tuteur.idTuteur) }}">
    <button class="btn">Delete</button>
</form>

templates/tuteur/_form.html.twig
{ _form.html.twig }
{% form_theme form _self %}

{% block _tuteur_nom_row %}
    <div class="form-group">
        {{ form_label(form.nom, 'Name') }}
        {{ form_widget(form.nom, { 'attr': {'class': 'form-control'} }) }}
        {{ form_errors(form.nom) }}
    </div>
{% endblock %}

{% block _tuteur_prenom_row %}
    <div class="form-group">
        {{ form_label(form.prenom, 'First Name') }}
        {{ form_widget(form.prenom, { 'attr': {'class': 'form-control'} }) }}
        {{ form_errors(form.prenom) }}
    </div>
{% endblock %}

{% block _tuteur_date_naisc_row %}
    <div class="form-group">
        {{ form_label(form.date_naisc, 'Date Of Birth') }}
        {{ form_widget(form.date_naisc, { 'attr': {'class': 'form-control'} }) }}
        {{ form_errors(form.date_naisc) }}
    </div>
{% endblock %}

{% block _tuteur_tlf_row %}
    <div class="form-group">
        {{ form_label(form.tlf, 'Phone Number') }}
        {{ form_widget(form.tlf, { 'attr': {'class': 'form-control'} }) }}
        {{ form_errors(form.tlf) }}
    </div>
{% endblock %}

{% block _tuteur_profession_row %}
    <div class="form-group">
        {{ form_label(form.profession, 'Profession') }}
        {{ form_widget(form.profession, { 'attr': {'class': 'form-control'} }) }}
        {{ form_errors(form.profession) }}
    </div>
{% endblock %}

{% block _tuteur_email_row %}
    <div class="form-group">
        {{ form_label(form.email, 'Email') }}
        {{ form_widget(form.email, { 'attr': {'class': 'form-control'} }) }}
        {{ form_errors(form.email) }}
    </div>
{% endblock %}

{% block _tuteur_image_row %}
    <div class="form-group">
        {{ form_label(form.image, 'Image') }}
        {{ form_widget(form.image, { 'attr': {'class': 'form-control-file'} }) }}
        {{ form_errors(form.image) }}
    </div>
{% endblock %}

templates/tuteur/edit.html.twig
{% extends '/back/gestion.html.twig' %}

{% block title %}Edit Tuteur{% endblock %}

{% block body %}
    <h1>Edit Tuteur</h1>

    {{ form_start(form) }}
        {{ form_row(form.nom) }}
        {{ form_row(form.prenom) }}
        {{ form_row(form.date_naisc) }}
        {{ form_row(form.tlf) }}
        {{ form_row(form.profession) }}
        {{ form_row(form.email) }}
        {{ form_row(form.image) }}

        <button type="submit" class="btn btn-primary">Save Changes</button>
    {{ form_end(form) }}
{% endblock %}

templates/tuteur/index.html.twig
{% extends '/front/gestion.html.twig' %}
{% block title %}Tuteurs{% endblock %}

{% block body %}
    <!-- Tuteurs Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Tutors</h6>
                <h1 class="mb-5">Tutors List</h1>
           
            <div class="row g-4">
                {% for tuteur in tuteurs %}
                    <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="team-item bg-light">
                            <div class="overflow-hidden">
                                <img class="img-fluid" src="{{ asset('images' ~ tuteur.image) }}" alt="">
                            </div>  
                            
                            <div class="text-center p-4">
                                <!-- Ajoutez ici les informations du tuteur -->
                                <h4 class="mb-0">{{ tuteur.nom }} {{ tuteur.prenom }}</h4>
                                <table class="table">
                                    <tbody>
                                    <tr>
                                        <th>Date Of Birth</th>
                                        <td>{{ tuteur.dateNaisc ? tuteur.dateNaisc|date('Y-m-d') : '' }}</td>
                                    </tr>
                                    <tr>
                                        <th>Phone Number</th>
                                        <td>{{ tuteur.tlf }}</td>
                                    </tr>
                                    <tr>
                                        <th>Profession</th>
                                        <td>{{ tuteur.profession }}</td>
                                    </tr>
                                    <tr>
                                        <th>Email</th>
                                        <td>{{ tuteur.email }}</td>
                                    </tr>
                                    </tbody>
                                </table>

                                
                               
                               
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/tuteur/new.html.twig
{% extends '/back/gestion.html.twig' %}

{% block title %}Create New Tuteur{% endblock %}

{% block body %}
    <h1>Create New Tuteur</h1>

    {{ form_start(form) }}
    {{ form_row(form.nom) }}
    {{ form_row(form.prenom) }}
    {{ form_row(form.date_naisc) }}
    {{ form_row(form.tlf) }}
    {{ form_row(form.profession) }}
    {{ form_row(form.email) }}
    {{ form_row(form.image, { 'required': true }) }}

    {# Affichage des erreurs de validation #}
    {% for error in form.vars.errors %}
        <div class="invalid-feedback">{{ error.message }}</div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Create</button>
    {{ form_end(form) }}
{% endblock %}

templates/tuteur/show.html.twig
{% extends '/back/gestion.html.twig' %}

{% block title %}Tuteur Details{% endblock %}

{% block body %}
    <h1>Tuteur Details</h1>

     </div>
             <div class="text-center mt-4">
                <a href="{{ path('app_tuteur_new') }}" class="btn btn-primary">Add New Tuteur</a>
            </div>
{% for tuteur in tuteur %}

    
    <dl class="row">
        

        <dt class="col-sm-3">Name:</dt>
        <dd class="col-sm-9">{{ tuteur.nom }}</dd>

        <dt class="col-sm-3">First Name:</dt>
        <dd class="col-sm-9">{{ tuteur.prenom }}</dd>

        <dt class="col-sm-3">Date Of Birth:</dt>
        <dd class="col-sm-9">{{ tuteur.dateNaisc ? tuteur.dateNaisc|date('Y-m-d') : '' }}</dd>

        <dt class="col-sm-3">Phone Number:</dt>
        <dd class="col-sm-9">{{ tuteur.tlf }}</dd>

        <dt class="col-sm-3">Profession:</dt>
        <dd class="col-sm-9">{{ tuteur.profession }}</dd>

        <dt class="col-sm-3">Email:</dt>
        <dd class="col-sm-9">{{ tuteur.email }}</dd>

        <dt class="col-sm-3">Image:</dt>
        <dd class="col-sm-9">
    {% if tuteur.image %}
                <img src="{{ asset(tuteur.image) }}" class="img-fluid">

            {% endif %}   

        </dd>
    </dl>
     <div class="text-center">
                                    <a href="{{ path('app_tuteur_edit', {'id_tuteur': tuteur.id_tuteur}) }}" class="btn btn-sm btn-info" title="Modifier">
                                        <i class="la la-pencil"></i>
                                    </a>
                                    <form action="{{ path('app_tuteur_delete', {'id_tuteur': tuteur.id_tuteur}) }}" method="post" class="d-inline">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tuteur.id_tuteur) }}">
                                        <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce tuteur ?')" title="Supprimer">
                                            <i class="la la-trash"></i>
                                        </button>
                                    </form>
                                </div>
    {% endfor %}

{% endblock %}